CREATE TABLE IF NOT EXISTS sheet_ingest_config (
    sheet_name VARCHAR(255) NOT NULL PRIMARY KEY,
    staging_table VARCHAR(255) NOT NULL,
    metadata_columns JSON NOT NULL,
    options JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
