CREATE TABLE `teach_record_raw` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `記錄狀態` VARCHAR(100) NULL,
  `日期` VARCHAR(100) NULL,
  `任教老師` VARCHAR(100) NULL,
  `學生編號` VARCHAR(100) NULL,
  `姓名` VARCHAR(100) NULL,
  `英文姓名` VARCHAR(100) NULL,
  `性別` VARCHAR(100) NULL,
  `學生級別` VARCHAR(100) NULL,
  `病房` VARCHAR(100) NULL,
  `病床` VARCHAR(100) NULL,
  `出勤 (來自出勤記錄輸入)` VARCHAR(100) NULL,
  `出勤` VARCHAR(100) NULL,
  `教學組別` VARCHAR(100) NULL,
  `科目` VARCHAR(100) NULL,
  `取代科目` VARCHAR(100) NULL,
  `教授科目` VARCHAR(255) NULL,
  `課程級別` VARCHAR(100) NULL,
  `教材` VARCHAR(100) NULL,
  `課題` VARCHAR(100) NULL,
  `教學重點1` VARCHAR(100) NULL,
  `教學重點2` VARCHAR(100) NULL,
  `教學重點3` VARCHAR(100) NULL,
  `教學重點4` VARCHAR(100) NULL,
  `自定課題` VARCHAR(100) NULL,
  `自定教學重點` TEXT NULL,
  `練習` VARCHAR(100) NULL,
  `上課時數` VARCHAR(100) NULL,
  `備註` TEXT NULL,
  `教學跟進/回饋` TEXT NULL,
  `file_hash` CHAR(64) NOT NULL,
  `batch_id` CHAR(36) NULL,
  `source_year` INT NULL,
  `ingested_at` DATETIME NOT NULL,
  UNIQUE KEY uniq_teach_record_file_hash (file_hash)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
